[package]
name = "specodezhda_management"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "2"
rusqlite = { version = "0.40.2", features = [
    "bundled",
    "functions",
    "time",
    "uuid",
] }
async-sqlite = { version = "0.6.0", features = [
    "array",
    "backup",
    "blob",
    "bundled",
    "cache",
    "time",
    "uuid",
    "vtab",
    "window",
] }
async-lock = "3.4.2"
uuid = { version = "1.26.1", features = ["v4"] }
time = { version = "0.3.55", features = ["formatting"] }

[dependencies.ohkami]
version = "0.24.9"
features = ["rt_smol"]
